language: python

matrix:
  fast_finish: true
  include:
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.5"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.6"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.8"

install:
  - pip install nose
  - python setup.py install

script:
  - nosetests -v -s .
